
# General settings
title: Webschool's Blog
description: >
  Feito pela comunidade para a comunidade.
baseurl: ''
url: 'Webschool-io.github.io'

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Dependencies
gems:
  - jekyll-mentions
  - jekyll-admin
  - jemoji

# Gems config
jekyll-mentions:
  base_url: https://github.com

# Links
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Cursos
    url: /cursos/
  - title: Autores
    url: /authors/
  - title: Tags
    url: /tags/
  - title: Escrever...
    url: /write/
  - title: Feed
    url: /feed.xml
